services:

  api:
    container_name: api
    build: ./api
    env_file:
      - ./api/.env.dev
    volumes: 
      - ./api/app:/opt/api/app
      - ./api/core/db:/opt/api/core/db
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 5s
    command: bash start.dev.sh
  
  db:
    container_name: db
    image: mysql:8.2
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/dev:/var/lib/mysql
    env_file:
      - ./db/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
    