services:

  api:
    container_name: api
    build: ./api
    env_file:
      - ./api/.env.dev
    volumes: 
      - ./api/app:/opt/api/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 5s
    command: >
      /opt/api/.venv/bin/uvicorn app.main:app
      --host 0.0.0.0
      --port 8080
      --reload
    
    