"""empty message

Revision ID: 0a3caa0538a5
Revises: 244448715014
Create Date: 2025-02-22 15:41:28.697600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0a3caa0538a5'
down_revision: Union[str, None] = '244448715014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('daily_walk_goal', sa.Integer(), nullable=False))
    op.add_column('dog', sa.Column('meal_pattern', sa.Enum('ONE_MEAL', 'TWO_MEALS', 'THREE_MEALS', 'FREE_FEEDING', name='dogmealpattern'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'meal_pattern')
    op.drop_column('dog', 'daily_walk_goal')
    # ### end Alembic commands ###
