"""empty message

Revision ID: 244448715014
Revises: 468513b145e0
Create Date: 2025-02-22 15:33:47.109320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '244448715014'
down_revision: Union[str, None] = '468513b145e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dog', 'species',
               existing_type=mysql.ENUM('POODLE', 'GOLDEN_RETRIEVER', 'BULLDOG', 'BEAGLE', 'GERMAN_SHEPHERD', 'SHIBA_INU', 'DACHSHUND', 'HUSKY', 'LABRADOR', 'CHIHUAHUA'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dog', 'species',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=32),
               type_=mysql.ENUM('POODLE', 'GOLDEN_RETRIEVER', 'BULLDOG', 'BEAGLE', 'GERMAN_SHEPHERD', 'SHIBA_INU', 'DACHSHUND', 'HUSKY', 'LABRADOR', 'CHIHUAHUA'),
               existing_nullable=True)
    # ### end Alembic commands ###
