"""empty message

Revision ID: 4f971bea7850
Revises: 0ea50eb43ac8
Create Date: 2025-03-02 09:36:46.269965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4f971bea7850'
down_revision: Union[str, None] = '0ea50eb43ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_schedule',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dog_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('medicine_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('daily_doses', sa.Integer(), nullable=False),
    sa.Column('dose_times', sa.JSON(), nullable=True),
    sa.Column('type', sa.Enum('ONCE', 'RECURRING', 'TEMPORARY', name='medtype'), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine_schedule')
    # ### end Alembic commands ###
