"""empty message

Revision ID: 5e391a8a3d86
Revises: 
Create Date: 2025-02-16 16:57:49.234218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5e391a8a3d86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('species', sa.Enum('POODLE', 'GOLDEN_RETRIEVER', 'BULLDOG', 'BEAGLE', 'GERMAN_SHEPHERD', 'SHIBA_INU', 'DACHSHUND', 'HUSKY', 'LABRADOR', 'CHIHUAHUA', name='dogspecies'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    # ### end Alembic commands ###
