"""empty message

Revision ID: 628d1f0836da
Revises: 0a3caa0538a5
Create Date: 2025-02-22 16:41:53.145818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '628d1f0836da'
down_revision: Union[str, None] = '0a3caa0538a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_record',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dog_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_record')
    # ### end Alembic commands ###
